import { AuthProvider } from "@/context/AuthContext";
import NavigationLayout from "@/utils/NavigationLayout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className="min-h-screen flex justify-between flex-col bg-white dark">
            <NavigationLayout>{children}</NavigationLayout>
            {/* <Footer/> */}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
